# Change these first
owner: ekoindia # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Eloka Webapp
    url: https://ekostore.app
  - name: Connect Webapp
    url: https://connect.eko.in
  - name: Connect Eloka Widget
    url: $CONNECT_ELOKA_WIDGET_URL
  - name: Eloka API
    url: $CONNECT_API_HEALTH_URL
    __dangerous__body_down_if_text_missing: '"status":"ok"'
  - name: Automaton
    url: $N8N_URL
    


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime
  logoUrl: https://eko.in/assets/img/eko-logo.svg
  name: Uptime
  introTitle: "**Uptime** Monitor"
  # introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/

i18n:
  footer: ""

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
